name: Deploy Logic App to Azure
on:
  workflow_call: 
    inputs:
        MODULE_NAME:
            type: string
            description: 'name of the logic app module e.g. cff'
            required: true
        SOURCE_PATH: 
            type: string
            description: 'path to the source of the logic app'
            required: true
        ENVIRONMENT:
            type: string
            required: true
            description: 'the indentifier of the environment in use e.g. dev, test, prod.'
        LOCATION:
            type: string
            required: false
            description: 'the name of the azure location being deployed to'
            default: ${{ vars.AZURE_LOCATION }}
        LOCATION_SHORT:
            type: string
            required: false
            description: 'the short name of the azure location being deployed to'
            default: ${{ vars.AZURE_LOCATION_SHORT }}
    secrets:
        AZURE_CREDENTIALS:
            required: true
env:
  LOGICAPP_NAME: "wvh${{ inputs.ENVIRONMENT }}-lapp-${{ inputs.MODULE_NAME }}"

jobs:
  Build:
    runs-on: ubuntu-privatenetworking
    steps:
      - uses: actions/checkout@v4
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ github.run_id }}.zip
          files: ${{ inputs.SOURCE_PATH }}
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.run_id }}.zip
  Deploy:
    name: Deploy
    runs-on: ubuntu-privatenetworking
    needs: [Build] 
    steps:
     - uses: azure/login@v1
       with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

     - uses: actions/download-artifact@master
       with:
        name: build-artifact
        path: build-art/

     - name: Deploy to Azure Logic App
       uses: Azure/functions-action@v1
       id: la
       with:
        app-name: ${{ env.LOGICAPP_NAME }}
        package: build-art/${{ github.run_id }}.zip
