name: 'Deploy Function App To Azure'
on:
  workflow_call:
    inputs:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: # the path to your web app project
        type: string
        description:  'the path to your web app project, defaults to the repository root'
        required: false
        default: '.'
      DOTNET_VERSION: 
        type: string
        description: 'the dotnet version to use'
        required: false
        default: '6.0.x' 
      BUILD_FILE: # the project file to build.
        type: string
        required: true
        description: 'the project file to build'
      FUNCTION_APP_NAME: # the name of the function app to deploy to.
        type: string
        required: true
        description: 'the name of the azure function app to deploy to.'
      ENVIRONMENT:
        type: string
        required: true
        description: 'the indentifier of the environment in use.'
    secrets:
      AZURE_PUBLISH_SECRET:
        required: true
      TF_API_TOKEN:
        required: true
jobs:
  plan-infrastructure:
    name: 'Plan Infrastructure'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Copy the modules folder into the working directory
    - name: Copy Modules
      run: cp -R ./terraform/modules ./terraform/${{ inputs.ENVIRONMENT }}-deploy/modules

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-deploy

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-deploy

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-deploy

  deploy-infrastructure:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: 'Deploy Infrastructure'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Copy the modules folder into the working directory
    - name: Copy Modules
      run: cp -R ./terraform/modules ./terraform/${{ inputs.ENVIRONMENT }}-deploy/modules

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-deploy

      # build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-deploy
    needs: plan-infrastructure

  build-and-deploy:
    name: Deploy Code
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ inputs.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build ${{ inputs.BUILD_FILE }} --configuration Release --output ./output
          popd
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PUBLISH_SECRET }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: '${{ inputs.FUNCTION_APP_NAME }}'
          slot-name: 'production'
          package: '${{ inputs.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
    needs: deploy-infrastructure

  plan-configure-infrastructure:
    name: 'Plan Configuration'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Copy the modules folder into the working directory
    - name: Copy Modules
      run: cp -R ./terraform/modules ./terraform/${{ inputs.ENVIRONMENT }}-configure/modules

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-configure

    # Checks that all Terraform configuration files adhere to a canonical format
    # - name: Terraform Format
    #   run: terraform fmt -check
    #   working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-configure      

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-configure
    needs: build-and-deploy

  deploy-configure-infrastructure:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: 'Deploy Configuration'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Copy the modules folder into the working directory
    - name: Copy Modules
      run: cp -R ./terraform/modules ./terraform/${{ inputs.ENVIRONMENT }}-configure/modules

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-configure

      # build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform/${{ inputs.ENVIRONMENT }}-configure
    needs: plan-configure-infrastructure
